Repository pytorch/glow, pull requests merged in 2018-10, with the labels that each got.

#1743 [onnxifi] Wrap onnxifi function names into macro.
  lib/Onnxifi/onnxifiGlow.cpp
Labels: CLA Signed

#1751 [cleanup] Allow getHandle on const Tensor.
  include/glow/Base/Tensor.h
  include/glow/Quantization/Base/Base.h
  lib/Quantization/Base/Base.cpp
Labels: CLA Signed

#1752 [Graph] Make Module non-copyable
  include/glow/Graph/Graph.h
  lib/Graph/Graph.cpp
  tests/unittests/OperatorTest.cpp
  tests/unittests/graphTest.cpp
Labels: CLA Signed

#1753 [Node] Add a setType method
  include/glow/Graph/Node.h
  lib/Graph/Node.cpp
  tests/unittests/graphTest.cpp
Labels: CLA Signed

#1754 [Tensor] Add a convertToType method
  include/glow/Base/Tensor.h
  lib/Base/Tensor.cpp
  tests/unittests/tensorsTest.cpp
Labels: CLA Signed

#1757 [travis.yml] Use keep_alive() instead of travis_wait
  .travis.yml
Labels: CLA Signed

#1759 [placeholders] Convert QuantizationProfileNode to placeholders
  examples/fr2en.cpp
  include/glow/Graph/Graph.h
  include/glow/Optimizer/Optimizer.h
  include/glow/Quantization/Quantization.h
  lib/Graph/Graph.cpp
  lib/IR/IRGen.cpp
  lib/Optimizer/Quantization.cpp
  lib/Quantization/Quantization.cpp
  tests/unittests/BackendTest.cpp
  tests/unittests/MLTest.cpp
  tests/unittests/graphTest.cpp
  tests/unittests/quantizationTest.cpp
  tools/ClassGen/NodeGen.cpp
  tools/loader/Loader.cpp
Labels: CLA Signed

#1746 [Caffe2] Implement DotProduct operator
  include/glow/Graph/Graph.h
  lib/Graph/Graph.cpp
  lib/Importer/Caffe2.cpp
  tests/models/caffe2Models/dot_product_predict_net.pbtxt
  tests/unittests/caffe2ImporterTest.cpp
Labels: CLA Signed

#1764 [travis] Add exit 1 on test failure
  .travis.yml
Labels: CLA Signed

#1768 [Backends.md] Add documentation on APIs for backends
  docs/Backends.md
Labels: CLA Signed

#1769 [ONNX] Raise error but don't die if auto_pads != VALID
  lib/Importer/ONNX.cpp
Labels: CLA Signed

#1770 [PH] Refactor the context definition outside of the loader. NFC.
  tools/loader/ImageClassifier.cpp
  tools/loader/Loader.cpp
  tools/loader/Loader.h
  tools/loader/ModelRunner.cpp
  tools/loader/TextTranslator.cpp
Labels: CLA Signed

#1775 [onnx] Glow does not support argmax output when pooling
  lib/Importer/ONNX.cpp
Labels: CLA Signed

#1771 [importer] Report error if reshape given with non-constant shape input
  include/glow/Importer/CommonOperatorLoader.h
Labels: CLA Signed

#1776 [trivial] Fixing linter warnings
  lib/Importer/ONNX.cpp
  lib/Optimizer/GraphOptimizer.cpp
Labels: CLA Signed

#1777 [Backend][Interpreter] Implement fp16 splat
  lib/Backends/Interpreter/InterpreterNodes.cpp
  tests/unittests/OperatorTest.cpp
Labels: CLA Signed

#1780 [Backend][Interpreter] Add a test case for FP16 transpose. NFC
  tests/unittests/OperatorTest.cpp
Labels: CLA Signed

#1779 [Backend][Interpreter] Implement fp16 avg pool
  lib/Backends/Interpreter/InterpreterFunction.h
  lib/Backends/Interpreter/InterpreterNodes.cpp
  tests/unittests/OperatorTest.cpp
Labels: CLA Signed

#1786 [Backend][Interpreter] Add a test case for FP16 tensor view. NFC.
  tests/unittests/OperatorTest.cpp
Labels: CLA Signed

#1788 [Backend][Interpreter] Implement FP16 SoftMax
  lib/Backends/Interpreter/InterpreterFunction.h
  lib/Backends/Interpreter/InterpreterNodes.cpp
  tests/unittests/OperatorTest.cpp
Labels: CLA Signed

#1789 [Backend][Interpreter] Implement FP16 MatMul
  lib/Backends/Interpreter/InterpreterFunction.h
  lib/Backends/Interpreter/InterpreterNodes.cpp
  tests/unittests/OperatorTest.cpp
Labels: CLA Signed

#1744 [Quantization] Add row-wise quantized FC for CPU backend
  include/glow/Graph/Graph.h
  lib/Backends/CPU/LLVMIRGen.cpp
  lib/Backends/CPU/libjit/libjit_matmul.cpp
  lib/Graph/Graph.cpp
  tests/unittests/OperatorTest.cpp
Labels: CLA Signed

#1794 [libjit] Make BroadcastFloat8 compatible with gcc 4.8.5
  lib/Backends/CPU/libjit/libjit_defs.h
Labels: CLA Signed

#1784 [include-bin] A tool to convert binary files to include-able char arrays
  tools/CMakeLists.txt
  tools/IncludeBin/CMakeLists.txt
  tools/IncludeBin/IncludeBin.cpp
Labels: CLA Signed

#1787 [Caffe2] Add support for Copy, EnsureCPUOutput, EnsureDense operators
  lib/Importer/Caffe2ModelLoader.cpp
Labels: CLA Signed

#1792 [Backend][Interpreter] Implement FP16 ElementMax
  lib/Backends/Interpreter/InterpreterFunction.h
  lib/Backends/Interpreter/InterpreterNodes.cpp
  tests/unittests/OperatorTest.cpp
Labels: CLA Signed

#1783 [PH] Port the C2/ONNX loader to using Placeholders.
  include/glow/ExecutionEngine/ExecutionEngine.h
  include/glow/Importer/Caffe2ModelLoader.h
  include/glow/Importer/CommonOperatorLoader.h
  include/glow/Importer/ONNXIFIModelLoader.h
  include/glow/Importer/ONNXModelLoader.h
  include/glow/Importer/ProtobufLoader.h
  lib/ExecutionEngine/ExecutionEngine.cpp
  lib/Importer/Caffe2ModelLoader.cpp
  lib/Importer/ONNXIFIModelLoader.cpp
  lib/Importer/ONNXModelLoader.cpp
  lib/Importer/ProtobufLoader.cpp
  lib/Onnxifi/Base.cpp
  lib/Onnxifi/Base.h
  tests/unittests/ImporterTestUtils.h
  tests/unittests/caffe2ImporterTest.cpp
  tests/unittests/onnxImporterTest.cpp
  tools/loader/ImageClassifier.cpp
  tools/loader/Loader.h
  tools/loader/ModelRunner.cpp
  tools/loader/TextTranslator.cpp
Labels: CLA Signed

#1798 [format] Run ./utils/format.sh fix
  lib/Importer/Caffe2ModelLoader.cpp
  lib/Onnxifi/Base.cpp
  tests/unittests/caffe2ImporterTest.cpp
  tests/unittests/onnxImporterTest.cpp
Labels: CLA Signed

#1796 [NFC][unittests][GraphScheduler] Avoid the use of a temporary std::vector
  tests/unittests/graphSchedulerTest.cpp
Labels: CLA Signed

#1799 [travis] Run unopt only for debug build.
  .travis.yml
Labels: CLA Signed

#1793 [Backend][Interpreter] Implement FP16 BatchedAdd
  lib/Backends/Interpreter/InterpreterFunction.h
  lib/Backends/Interpreter/InterpreterNodes.cpp
  tests/unittests/OperatorTest.cpp
Labels: CLA Signed

#1782 [GraphOptimizer] Move transpose constant folding optimization before merging BatchNorm into Convolution
  lib/Optimizer/GraphOptimizer.cpp
  tests/unittests/graphOptzTest.cpp
Labels: CLA Signed

#1790 CPU: change the way that we generate the JIT runtime
  lib/Backends/CPU/CMakeLists.txt
Labels: CLA Signed

#1803 [ONNXIFI] Add a getter to silence the unused var warning. NFC.
  lib/Onnxifi/Base.h
Labels: CLA Signed

#1802 [cleanup] Simplify the SaveNode builder. NFC.
  examples/char-rnn.cpp
  examples/cifar10.cpp
  examples/fr2en.cpp
  examples/mnist.cpp
  examples/ptb.cpp
  include/glow/Graph/Graph.h
  lib/Graph/Graph.cpp
  tests/unittests/BackendTest.cpp
  tests/unittests/BackendTestUtils.cpp
  tests/unittests/GemmTest.cpp
  tests/unittests/HyphenTest.cpp
  tests/unittests/MLTest.cpp
  tests/unittests/OperatorTest.cpp
  tests/unittests/gradCheckTest.cpp
  tests/unittests/graphGradTest.cpp
  tests/unittests/graphOptzTest.cpp
  tests/unittests/graphTest.cpp
  tests/unittests/partitionTest.cpp
  tests/unittests/quantizationTest.cpp
Labels: CLA Signed

#1806 [BackendTestUtils.h | cleanup] Remove deleted functions' declarations
  tests/unittests/BackendTestUtils.h
Labels: CLA Signed

#1774 [Caffe2] Implement BatchBoxCox Caffe2 operator
  include/glow/Graph/Graph.h
  lib/Backends/Interpreter/InterpreterFunction.h
  lib/Backends/Interpreter/InterpreterNodes.cpp
  lib/Graph/Graph.cpp
  lib/Importer/Caffe2ModelLoader.cpp
  tests/models/caffe2Models/batch_box_cox_predict_net.pbtxt
  tests/unittests/caffe2ImporterTest.cpp
Labels: CLA Signed

#1773 [Caffe2] Support FCTransposed op.
  lib/Importer/Caffe2ModelLoader.cpp
  tests/models/caffe2Models/fcTransposed_init_net.pbtxt
  tests/models/caffe2Models/fcTransposed_predict_net.pbtxt
  tests/models/caffe2Models/fc_init_net.pbtxt
  tests/models/caffe2Models/fc_predict_net.pbtxt
  tests/unittests/caffe2ImporterTest.cpp
Labels: CLA Signed

#1809 [doc] Update the docs and mention constants and placeholders.
  docs/IR.md
Labels: CLA Signed

#1811 Remove VisibilityKind from WeightVar.
  include/glow/Base/Traits.h
  include/glow/IR/IRBuilder.h
  include/glow/IR/Instrs.h
  lib/Backends/CPU/AllocationsInfo.cpp
  lib/IR/IRBuilder.cpp
  lib/IR/IRGen.cpp
  lib/Optimizer/IROptimizer.cpp
Labels: CLA Signed

#1810 Support autoIRGen for nodes with multiple results in InstrGen
  tools/ClassGen/InstrBuilder.cpp
Labels: CLA Signed

#1813 [Graph] Fix verify one writer
  lib/Graph/Graph.cpp
  tests/unittests/graphTest.cpp
Labels: CLA Signed

#1814 [Graph] Verify that Constants are never written to
  lib/Graph/Graph.cpp
  tests/unittests/graphTest.cpp
Labels: CLA Signed

#1651 Adding inference tests for TF ONNX models
  tests/images/imagenet_299/cat_281_299.png
  tests/images/imagenet_299/dog_207_299.png
  tests/images/imagenet_299/zebra_340_299.png
  tests/images/run.sh
  tools/loader/ImageClassifier.cpp
Labels: CLA Signed

#1819 [fix] Fix calls to onnxifi methods.
  lib/Onnxifi/onnxifiGlow.cpp
Labels: CLA Signed

#1818 [GraphOptimizer] Updates to reflect Variable migration
  lib/Optimizer/GraphOptimizer.cpp
Labels: CLA Signed

#1824 [Imagenet tests] Add cmake rule for imagenet_299 directory.
  tests/images/CMakeLists.txt
Labels: CLA Signed

#1821 [Converter] Introduce a FunctionConverter helper class
  include/glow/Converter/FunctionConverter.h
  lib/CMakeLists.txt
  lib/Converter/CMakeLists.txt
  lib/Converter/FunctionConverter.cpp
Labels: CLA Signed

#1826 [Function] Fix a nasty bug in eraseNode(Node *)
  lib/Graph/Graph.cpp
  tests/unittests/graphTest.cpp
Labels: CLA Signed

#1825 [unittests] New BackendCorrectnessTest API enabling easy quantization
  tests/unittests/BackendCorrectnessTest.cpp
  tests/unittests/BackendTestUtils.cpp
  tests/unittests/BackendTestUtils.h
  tests/unittests/CMakeLists.txt
  tests/unittests/OCLTest.cpp
Labels: CLA Signed

#1829 [build_llvm] Build LLVM in Release mode to reduce memory pressure
  utils/build_llvm.sh
Labels: CLA Signed

#1831 [cpu] Add some missing LLVM deps to CPUBackend
  lib/Backends/CPU/CMakeLists.txt
Labels: CLA Signed

#1828 [travis] Cache what's possible to speed up the build
  .travis.yml
  utils/install_protobuf.sh
Labels: CLA Signed

#1835 [CI] Make dummy circleci config to avoid failures on master.
  .circleci/config.yml
Labels: CLA Signed

#1841 [ONNXIFI] Don't mangle the name of ONNXIFI interface functions
  lib/Onnxifi/onnxifiGlow.cpp
Labels: CLA Signed

#1840 [trivial] Add parens to silence warning from g++
  lib/Graph/Graph.cpp
Labels: CLA Signed

#1843 [trivial] Make diff output better
  utils/format.sh
Labels: CLA Signed

#1845 Fixes float literals for MSVC.
  tests/unittests/OperatorTest.cpp
  tests/unittests/caffe2ImporterTest.cpp
Labels: CLA Signed

#1842 [ONNXIFI] Fix resnet50 integration test
  lib/Importer/ONNXIFIModelLoader.cpp
Labels: CLA Signed

#1850 Fixes GlowJIT.cpp for MSVC.
  lib/Backends/CPU/GlowJIT.cpp
Labels: CLA Signed

#1846 Allow findSymbol to find non-exported symbols
  lib/Backends/CPU/GlowJIT.cpp
Labels: CLA Signed

#1822 [Quantization] Specialize the FunctionConverter to quantize a function
  lib/Quantization/CMakeLists.txt
  lib/Quantization/Quantization.cpp
  tests/unittests/quantizationTest.cpp
Labels: CLA Signed

#1852 CPUBackend: add a comment for the symbol lookup
  lib/Backends/CPU/GlowJIT.cpp
Labels: CLA Signed

#1856 [Trivial] Minimal configuration to make CircleCI happy
  .circleci/config.yml
Labels: CLA Signed

#1863 [ImageClassifier] Add option for printing the top-k labels
  tools/loader/ImageClassifier.cpp
Labels: CLA Signed

#1847 Disable CPURuntimeNative for MSVC
  lib/Backends/CPU/CMakeLists.txt
  tests/benchmark/CMakeLists.txt
  tests/unittests/CMakeLists.txt
Labels: CLA Signed

#1857 [GraphOptimizer] Fix the Conv-BatchNorm optimization
  lib/Optimizer/GraphOptimizer.cpp
  tests/unittests/graphOptzTest.cpp
Labels: CLA Signed

#1853 [Importer] Support arg "order" in Caffe2 Conv, MaxPool and AveragePool ops
  lib/Importer/Caffe2ModelLoader.cpp
  tests/models/caffe2Models/avgpool_nhwc_predict_net.pbtxt
  tests/models/caffe2Models/avgpool_predict_net.pbtxt
  tests/models/caffe2Models/conv_nhwc_init_net.pbtxt
  tests/models/caffe2Models/conv_nhwc_predict_net.pbtxt
  tests/models/caffe2Models/maxpool_nhwc_predict_net.pbtxt
  tests/models/caffe2Models/maxpool_predict_net.pbtxt
  tests/unittests/caffe2ImporterTest.cpp
Labels: CLA Signed

#1864 [trivial] Remove trailing whitespace
  .clang-format
  .travis/run_coverage.sh
  CMakeLists.txt
  cmake/modules/CoverageSupport.cmake
  cmake/modules/GlowTestSupport.cmake
  cmake/modules/SanitizerSupport.cmake
  docs/NewBackendSpecificNode.md
  lib/Backends/OpenCL/CMakeLists.txt
  lib/Importer/CMakeLists.txt
  tests/models/caffe2Models/clip_op_default_net.pbtxt
  tests/models/caffe2Models/clip_op_net.pbtxt
  tests/models/caffe2Models/fcTransposed_init_net.pbtxt
  tests/models/caffe2Models/fc_init_net.pbtxt
  utils/scripts/gen_caffe2_model.py
Labels: CLA Signed

#1867 [NodeGen] Update the docstring for ConvertToNode. NFC
  tools/ClassGen/NodeGen.cpp
Labels: CLA Signed

#1859 [caffe2ImporterTest] Add eq unittest to caffe2ImporterTest
  tests/models/caffe2Models/eq_op_net.pbtxt
  tests/unittests/caffe2ImporterTest.cpp
Labels: CLA Signed

#1871 [Bundle] Fix Resnet50 Bundle to support Placeholder Migration
  lib/Backends/CPU/AllocationsInfo.cpp
  lib/Backends/CPU/BundleSaver.cpp
Labels: CLA Signed

#1874 [Placeholders/Constants] Remove last entry of variables from loaders.
  include/glow/Importer/CommonOperatorLoader.h
  include/glow/Importer/ProtobufLoader.h
  lib/Importer/Caffe2ModelLoader.cpp
  lib/Importer/ONNXModelLoader.cpp
  lib/Importer/ProtobufLoader.cpp
Labels: CLA Signed

#1866 [Loader] Add an option to run a model in fp16
  tools/loader/CMakeLists.txt
  tools/loader/Loader.cpp
Labels: CLA Signed

#1875 [NFC/cleanup] Remove more entries of variables.
  examples/char-rnn.cpp
  examples/cifar10.cpp
  examples/fr2en.cpp
  include/glow/ExecutionEngine/ExecutionEngine.h
  lib/Converter/FunctionConverter.cpp
  lib/ExecutionEngine/ExecutionEngine.cpp
  lib/Graph/Graph.cpp
  lib/IR/GraphScheduler.cpp
  lib/Onnxifi/Base.cpp
  lib/Optimizer/IROptimizer.cpp
  lib/Optimizer/Lower.cpp
  lib/Optimizer/Partition.cpp
  tests/unittests/BackendTest.cpp
  tests/unittests/BackendTestUtils.cpp
  tests/unittests/GemmTest.cpp
  tests/unittests/HyphenTest.cpp
  tests/unittests/MLTest.cpp
  tests/unittests/OperatorTest.cpp
  tests/unittests/caffe2ImporterTest.cpp
  tests/unittests/gradCheckTest.cpp
  tests/unittests/graphTest.cpp
  tests/unittests/onnxImporterTest.cpp
  tests/unittests/partitionTest.cpp
  tools/loader/ImageClassifier.cpp
  tools/loader/TextTranslator.cpp
Labels: CLA Signed

#1872 [GraphOptimizer] Do transpose and reshape optimizations first
  lib/Optimizer/GraphOptimizer.cpp
Labels: CLA Signed

#1878 [ImageClassifier | NFC] Improve topK label printing
  tools/loader/ImageClassifier.cpp
Labels: CLA Signed

#1879 [onnxifi] Add support for clip operator.
  lib/Importer/ONNXIFIModelLoader.cpp
  lib/Importer/ONNXModelLoader.cpp
  tests/models/onnxModels/clip.onnxtxt
  tests/unittests/onnxImporterTest.cpp
Labels: CLA Signed

#1882 [ONNXifi] Add support for BatchBoxCox operator
  lib/Importer/ONNXIFIModelLoader.cpp
  lib/Importer/ONNXModelLoader.cpp
  tests/models/onnxModels/batchBoxCox.onnxtxt
  tests/unittests/onnxImporterTest.cpp
Labels: CLA Signed

#1881 Add benchmark for convolution
  tests/benchmark/CMakeLists.txt
  tests/benchmark/ConvBench.cpp
Labels: CLA Signed

#1870 [ONNXifi] Make onnxRunGraph execute Glow graph asynchronously
  lib/Onnxifi/Base.cpp
  lib/Onnxifi/Base.h
  lib/Onnxifi/CMakeLists.txt
  lib/Onnxifi/ThreadPool.cpp
  lib/Onnxifi/ThreadPool.h
  lib/Onnxifi/onnxifiGlow.cpp
  tests/unittests/CMakeLists.txt
  tests/unittests/onnxifiThreadPoolTest.cpp
Labels: CLA Signed

#1833 [CI] Migrate Glow from Travis to CircleCI. Enable ONNXIFI tests on Glow.
  .circleci/build.sh
  .circleci/config.yml
  .circleci/test.sh
  .travis.yml
  .travis/run_tests.sh
Labels: CLA Signed, WORK IN PROGRESS

#1890 Call out Apache2 license in README.md
  README.md
Labels: CLA Signed

#1892 Silence Apple's warning about the deprecation of OpenCL
  lib/Backends/OpenCL/OpenCL.cpp
Labels: CLA Signed

#1883 [onnxifi] Add DotProduct to ONNX parser.
  lib/Importer/ONNXIFIModelLoader.cpp
  lib/Importer/ONNXModelLoader.cpp
  tests/models/onnxModels/dot_product.onnxtxt
  tests/unittests/onnxImporterTest.cpp
Labels: CLA Signed

#1889 [onnxifi] Some cleanups and supply number of workers.
  lib/Onnxifi/Base.h
  lib/Onnxifi/ThreadPool.cpp
  lib/Onnxifi/onnxifiGlow.cpp
Labels: CLA Signed

#1893 [trivial] Remove non-ASCII in docs/IR.md
  docs/IR.md
Labels: CLA Signed

#1891 [graph] Implement LengthsToRanges (interp only)
  include/glow/Graph/Graph.h
  lib/Backends/Interpreter/InterpreterNodes.cpp
  lib/Graph/Graph.cpp
  lib/Graph/Nodes.cpp
  tests/unittests/OperatorTest.cpp
  tools/ClassGen/InstrGen.cpp
  tools/ClassGen/NodeGen.cpp
Labels: CLA Signed

#1900 [Import] Support Sum with 1 Input
  include/glow/Importer/CommonOperatorLoader.h
  tests/models/onnxModels/sum1.onnxtxt
  tests/unittests/onnxImporterTest.cpp
Labels: CLA Signed

#1902 [cpu] Implement LengthsToRanges
  lib/Backends/CPU/LLVMIRGen.cpp
  lib/Backends/CPU/libjit/libjit.cpp
  tests/unittests/OperatorTest.cpp
Labels: CLA Signed

#1894 [caffe2] Import LengthsToRanges
  lib/Graph/Nodes.cpp
  lib/Importer/Caffe2ModelLoader.cpp
  tests/models/caffe2Models/lengths_to_ranges.pbtxt
  tests/models/caffe2Models/lengths_to_ranges_init_net.pbtxt
  tests/unittests/caffe2ImporterTest.cpp
Labels: CLA Signed

#1901 [onnx importer] Import LengthsToRanges
  lib/Importer/ONNXIFIModelLoader.cpp
  lib/Importer/ONNXModelLoader.cpp
  tests/models/onnxModels/lengths_to_ranges.onnxtxt
  tests/unittests/onnxImporterTest.cpp
Labels: CLA Signed

#1897 [Caffe2] Add support for SparseToDense operator
  include/glow/Graph/Graph.h
  lib/Backends/Interpreter/InterpreterNodes.cpp
  lib/Graph/Graph.cpp
  lib/Graph/Nodes.cpp
  lib/Importer/Caffe2ModelLoader.cpp
  tests/models/caffe2Models/sparse_to_dense.pbtxt
  tests/unittests/OperatorTest.cpp
  tests/unittests/caffe2ImporterTest.cpp
  tools/ClassGen/InstrGen.cpp
  tools/ClassGen/NodeGen.cpp
Labels: CLA Signed

#1880 [ONNXifi] Add support for ReplaceNaN operator
  lib/Importer/ONNXIFIModelLoader.cpp
  lib/Importer/ONNXModelLoader.cpp
  tests/models/onnxModels/replaceNaN.onnxtxt
  tests/unittests/onnxImporterTest.cpp
Labels: CLA Signed

#1912 [Caffe2 Importer] Add NCHW2NHWC Caffe2 op.
  lib/Importer/Caffe2ModelLoader.cpp
  tests/models/caffe2Models/NCHW2NHWC_predict_net.pbtxt
  tests/unittests/caffe2ImporterTest.cpp
Labels: CLA Signed

#1917 [converter][easy] Assert destTy == dstKind_ when converting
  lib/Converter/TypeAToTypeBFunctionConverter.cpp
Labels: CLA Signed

#1919 [ONNX] Support Add with more than 2 inputs
  include/glow/Importer/CommonOperatorLoader.h
  tests/models/onnxModels/sumN.onnxtxt
  tests/unittests/onnxImporterTest.cpp
Labels: CLA Signed

#1906 [cmake] Fix a bunch of dependencies so BUILD_SHARED_LIBS works
  CMakeLists.txt
  examples/CMakeLists.txt
  lib/CodeGen/CMakeLists.txt
  lib/Graph/CMakeLists.txt
  lib/IR/CMakeLists.txt
  lib/Onnxifi/CMakeLists.txt
  lib/Quantization/CMakeLists.txt
  lib/Support/CMakeLists.txt
  tests/unittests/CMakeLists.txt
  tools/loader/CMakeLists.txt
Labels: CLA Signed

#1922 Revert "[cmake] Fix a bunch of dependencies so BUILD_SHARED_LIBS work"
  CMakeLists.txt
  examples/CMakeLists.txt
  lib/CodeGen/CMakeLists.txt
  lib/Graph/CMakeLists.txt
  lib/IR/CMakeLists.txt
  lib/Onnxifi/CMakeLists.txt
  lib/Quantization/CMakeLists.txt
  lib/Support/CMakeLists.txt
  tests/unittests/CMakeLists.txt
  tools/loader/CMakeLists.txt
Labels: CLA Signed

#1910 [ImageClassifier] Add option for streaming input filenames
  tools/loader/ImageClassifier.cpp
Labels: CLA Signed

#1923 [Operator] Support BatchOneHot
  include/glow/Graph/Graph.h
  include/glow/Importer/CommonOperatorLoader.h
  lib/Backends/Interpreter/InterpreterFunction.h
  lib/Backends/Interpreter/InterpreterNodes.cpp
  lib/Graph/Graph.cpp
  lib/Graph/Nodes.cpp
  tests/unittests/OperatorTest.cpp
  tools/ClassGen/InstrGen.cpp
  tools/ClassGen/NodeGen.cpp
Labels: CLA Signed

#1924 [unittests] Fix FP16QuantizeAndDequantize
  tests/unittests/OperatorTest.cpp
Labels: CLA Signed

#1918 [ONNX] Add ONNX support for SparseToDense operator
  lib/Backends/CPU/LLVMIRGen.cpp
  lib/Backends/CPU/libjit/libjit.cpp
  lib/Importer/ONNXIFIModelLoader.cpp
  lib/Importer/ONNXModelLoader.cpp
  tests/models/onnxModels/sparseToDense.onnxtxt
  tests/unittests/OperatorTest.cpp
  tests/unittests/onnxImporterTest.cpp
Labels: CLA Signed

#1926 Mark quantize, dequantize and rescale_quantized as data-parallel operations
  lib/Backends/CPU/LLVMIRGen.cpp
  lib/Backends/CPU/libjit/libjit.cpp
  lib/Backends/OpenCL/OpenCL.cpp
  tools/ClassGen/InstrGen.cpp
Labels: CLA Signed

#1876 [Quantization] Support int32 quantized bias for quantized Conv
  include/glow/Quantization/Base/Base.h
  lib/Backends/CPU/LLVMIRGen.cpp
  lib/Backends/CPU/libjit/libjit.cpp
  lib/Backends/CPU/libjit/libjit_conv.cpp
  lib/Backends/Interpreter/InterpreterNodes.cpp
  lib/Backends/OpenCL/kernels.cl
  lib/Backends/OpenCL/kernels_fwd_quantized_conv.cl
  lib/Graph/Graph.cpp
  lib/Graph/Nodes.cpp
  lib/IR/Instrs.cpp
  lib/Optimizer/GraphOptimizer.cpp
  lib/Quantization/Base/Base.cpp
  lib/Quantization/Quantization.cpp
  tests/unittests/BackendCorrectnessTest.cpp
  tests/unittests/OperatorTest.cpp
  tests/unittests/graphTest.cpp
  tools/ClassGen/Backends/OpenCL/OpenCLSpecificInstrs.h
  tools/ClassGen/InstrGen.cpp
Labels: CLA Signed

#1899 [Graph] Implement Logit operator
  include/glow/Graph/Graph.h
  lib/Graph/Graph.cpp
  lib/Importer/Caffe2ModelLoader.cpp
  tests/models/caffe2Models/logit_op_net.pbtxt
  tests/unittests/OperatorTest.cpp
  tests/unittests/caffe2ImporterTest.cpp
Labels: CLA Signed

#1929 [Clean up] Clean up the unused code.
  lib/Backends/Interpreter/InterpreterNodes.cpp
Labels: CLA Signed

#1932 [OperatorTest][fix] Do not run logit test on OCL
  tests/unittests/OperatorTest.cpp
Labels: CLA Signed

#1930 [Float16] Add a few operators that are needed for the interpreter support
  include/glow/Support/Float16.h
  tests/unittests/float16Test.cpp
Labels: CLA Signed

#1934 Run a round of DCE before any other graph optimizations
  lib/Optimizer/GraphOptimizer.cpp
  tests/unittests/graphOptzTest.cpp
Labels: CLA Signed

#1936 Add a getter ExecutionEngine::getCompiledFunction
  include/glow/ExecutionEngine/ExecutionEngine.h
Labels: CLA Signed

#1925 [Caffe2/ONNX] Add support for LengthsSum operator
  include/glow/Graph/Graph.h
  include/glow/Importer/CommonOperatorLoader.h
  lib/Backends/CPU/LLVMIRGen.cpp
  lib/Backends/CPU/libjit/libjit.cpp
  lib/Backends/Interpreter/InterpreterNodes.cpp
  lib/Graph/Graph.cpp
  lib/Graph/Nodes.cpp
  lib/Importer/ONNXIFIModelLoader.cpp
  tests/models/caffe2Models/lengths_sum.pbtxt
  tests/models/onnxModels/lengths_sum.onnxtxt
  tests/unittests/OperatorTest.cpp
  tests/unittests/caffe2ImporterTest.cpp
  tests/unittests/onnxImporterTest.cpp
  tools/ClassGen/InstrGen.cpp
  tools/ClassGen/NodeGen.cpp
Labels: CLA Signed

#1920 running an ONNX model exported from PyTorch pretrained model
  docs/ModelLoader.md
  utils/export_onnx_model.py
Labels: CLA Signed

#1927 [ONNXLoader] Handle FCTransposed op type.
  lib/Importer/ONNXIFIModelLoader.cpp
  lib/Importer/ONNXModelLoader.cpp
  tests/models/onnxModels/FCTransposed.onnxtxt
  tests/unittests/onnxImporterTest.cpp
Labels: CLA Signed

#1941 docs: introduce a dictionary of lexicon
  docs/Lexicon.md
Labels: CLA Signed

#1913 [Image] Fix writePngImage 90 degree rotation and black image output issues
  lib/Base/Image.cpp
  tests/unittests/CMakeLists.txt
  tests/unittests/imageTest.cpp
Labels: CLA Signed

#1940 [Quantization] Support int32 quantized bias of FullyConnected.
  lib/Backends/CPU/LLVMIRGen.cpp
  lib/Backends/CPU/libjit/libjit.cpp
  lib/Backends/Interpreter/InterpreterNodes.cpp
  lib/Backends/OpenCL/OpenCL.cpp
  lib/Backends/OpenCL/kernels.cl
  lib/Graph/Nodes.cpp
  lib/Quantization/Quantization.cpp
  tests/unittests/OperatorTest.cpp
  tests/unittests/graphTest.cpp
Labels: CLA Signed, jit

#1942 [docs] add some ML specific terminology
  docs/Lexicon.md
Labels: CLA Signed

#1928 [onnxifi] Throttle input concurrency with fixed number of threads on Glow side, configured per backend.
  lib/Onnxifi/Base.cpp
  lib/Onnxifi/Base.h
  lib/Onnxifi/onnxifiGlow.cpp
Labels: CLA Signed

#1946 [docs] add some collaboration and compiler terminology
  docs/Lexicon.md
Labels: CLA Signed
