Repository pytorch/glow, pull requests merged in 2018-11, with the labels that each got.

#1931 [WIP]Full fp16 interpreter
  lib/Backends/Interpreter/InterpreterFunction.h
  lib/Backends/Interpreter/InterpreterNodes.cpp
Labels: CLA Signed

#1943 Migrate CPU Backend to allocate memory at runtime.
  docs/JIT.md
  include/glow/Backends/CompiledFunction.h
  lib/Backends/CPU/AllocationsInfo.cpp
  lib/Backends/CPU/AllocationsInfo.h
  lib/Backends/CPU/BundleSaver.cpp
  lib/Backends/CPU/CPUBackend.cpp
  lib/Backends/CPU/CPUFunction.cpp
  lib/Backends/CPU/CPUFunction.h
  lib/Backends/CPU/DebugInfo.cpp
  lib/Backends/CPU/LLVMIRGen.cpp
  lib/ExecutionEngine/ExecutionEngine.cpp
Labels: CLA Signed

#1937 [GraphScheduler] Add a simple topological sort graph scheduler
  lib/IR/CMakeLists.txt
  lib/IR/ChildMemSizeBasedScheduler.cpp
  lib/IR/GraphScheduler.cpp
  lib/IR/GraphScheduler.h
  lib/IR/TopologicalSortBasedScheduler.cpp
  tests/unittests/graphSchedulerTest.cpp
Labels: CLA Signed

#1955 [docs] Update docs/Lexicon.md
  docs/Lexicon.md
Labels: CLA Signed

#1956 [fix] Fix memory leak when allocate Tensor object.
  lib/Onnxifi/Base.cpp
Labels: CLA Signed

#1960 Fix memory allocation issue when we don't have constant weights
  lib/Backends/CPU/AllocationsInfo.cpp
Labels: CLA Signed

#1963 [memory leak] Fix memory leak when parsing onnx model
  lib/Importer/ONNXIFIModelLoader.cpp
Labels: CLA Signed

#1966 Fix overflow of Sigmoid in CPU Backend
  lib/Backends/CPU/libjit/libjit.cpp
  tests/unittests/OperatorTest.cpp
Labels: CLA Signed, jit

#1964 [cpu] Implement SparseLengthsWeightedSum
  lib/Backends/CPU/LLVMIRGen.cpp
  lib/Backends/CPU/libjit/libjit.cpp
  tests/unittests/OperatorTest.cpp
Labels: CLA Signed, jit

#1957 [trivial] Add RAUW (Replace All Uses With) to the lexicon
  docs/Lexicon.md
Labels: CLA Signed

#1969 [fix] Do not allocate memory when size is 0 for CPU backend.
  lib/Backends/CPU/CPUFunction.cpp
  lib/Backends/CPU/CPUFunction.h
Labels: CLA Signed

#1972 Unifying import of SparseLengthsSum and SparseLengthsWeightedSum
  include/glow/Importer/CommonOperatorLoader.h
  lib/Importer/Caffe2ModelLoader.cpp
  lib/Importer/ONNXIFIModelLoader.cpp
Labels: CLA Signed

#1974 [Tensor] Make dumpImpl(Tensor*) take a const ptr
  include/glow/Base/Tensor.h
  lib/Base/Tensor.cpp
Labels: CLA Signed

#1983 [trivial][docs] Update the link to code of conduct.
  CODE_OF_CONDUCT.md
Labels: CLA Signed

#1978 [base] Utility functions for reading/writing binary tensor blobs
  include/glow/Base/IO.h
  lib/Base/CMakeLists.txt
  lib/Base/IO.cpp
  tests/unittests/CMakeLists.txt
  tests/unittests/UtilsTest.cpp
Labels: CLA Signed

#1958 Moved OpenCL memory allocation to runtime.
  include/glow/Backends/BackendUtils.h
  lib/Backends/BackendUtils.cpp
  lib/Backends/CMakeLists.txt
  lib/Backends/OpenCL/OpenCL.cpp
  lib/Backends/OpenCL/OpenCL.h
  lib/ExecutionEngine/ExecutionEngine.cpp
Labels: CLA Signed

#1984 [easy] Clean up temporary files
  lib/Graph/Graph.cpp
  tests/unittests/quantizationTest.cpp
Labels: CLA Signed

#1981 [quantization][trivial] Put FunctionQuantizer in anonymous namespace
  lib/Quantization/Quantization.cpp
Labels: CLA Signed

#1959 [Quantization] Enabling quantization profiling in CPU bakend.
  lib/Backends/CPU/LLVMIRGen.cpp
  lib/Backends/CPU/libjit/libjit.cpp
  tests/unittests/quantizationTest.cpp
Labels: jit

#1994 [ImageClassifier] Fix convert-inout-to-fp16
  tools/loader/ImageClassifier.cpp
Labels: CLA Signed

#1993 [Verifier] Switch the node verifier from assert to returning bool for the nodes
  include/glow/Graph/Node.h
  include/glow/Graph/Nodes.h
  include/glow/Graph/VerifierHelper.h
  include/glow/Support/Support.h
  lib/Graph/CMakeLists.txt
  lib/Graph/Graph.cpp
  lib/Graph/Node.cpp
  lib/Graph/Nodes.cpp
  lib/Graph/VerifierHelper.cpp
  lib/Support/Support.cpp
  tests/unittests/graphTest.cpp
  tools/ClassGen/Backends/CPU/CPUSpecificNodesVerification.h
  tools/ClassGen/Backends/OpenCL/OpenCLSpecificNodesVerification.h
  tools/ClassGen/NodeBuilder.cpp
Labels: CLA Signed

#1991 Import BatchMatMul to ONNX
  include/glow/Importer/CommonOperatorLoader.h
  lib/Importer/Caffe2ModelLoader.cpp
  lib/Importer/ONNXIFIModelLoader.cpp
  tests/models/onnxModels/batch_matmul.onnxtxt
  tests/unittests/onnxImporterTest.cpp
Labels: CLA Signed

#1995 [jit] Restore the functionality for dumping JIT symbols that got lost during the LLVM6 to LLVM7 transition
  lib/Backends/CPU/GlowJIT.cpp
Labels: CLA Signed, jit

#1996 [fixes] Various fixes: openCL test, init histogram with 0.
  lib/Backends/CPU/LLVMIRGen.cpp
  lib/Backends/CPU/libjit/libjit.cpp
  lib/Quantization/Base/Profile.cpp
  tests/unittests/quantizationTest.cpp
Labels: CLA Signed, jit

#1980 [runtime] Moved context use to runtime for Interpreter Backend
  include/glow/Backends/CompiledFunction.h
  lib/Backends/Interpreter/CMakeLists.txt
  lib/Backends/Interpreter/Interpreter.cpp
  lib/Backends/Interpreter/InterpreterFunction.cpp
  lib/Backends/Interpreter/InterpreterFunction.h
Labels: CLA Signed

#1999 [FunctionQuantizer] Fix rescaling happening in the middle of nodes
  lib/Graph/Nodes.cpp
  lib/Quantization/Quantization.cpp
  tests/unittests/quantizationTest.cpp
Labels: CLA Signed

#2000 [ONNX] Support load of int32 Tensor
  lib/Importer/ONNXModelLoader.cpp
  tests/models/onnxModels/constant.onnxtxt
  tests/unittests/onnxImporterTest.cpp
Labels: CLA Signed

#2002 [fix] Fix types for handles.
  lib/Importer/ONNXModelLoader.cpp
Labels: CLA Signed

#2005 [BackendUtils] Fix BackendUtils allocation
  lib/Backends/BackendUtils.cpp
  lib/Backends/Interpreter/InterpreterFunction.cpp
  lib/Backends/OpenCL/OpenCL.cpp
Labels: CLA Signed

#2004 [ImageClassifier] Change 0to256 to 0to255
  tests/images/run.sh
  tools/loader/ImageClassifier.cpp
Labels: CLA Signed

#2006 Bump docker image to 230 in circle CI
  .circleci/config.yml
Labels: CLA Signed

#2014 [common loader] Move Clip and SparseToDense to common parsing.
  include/glow/Importer/CommonOperatorLoader.h
  lib/Importer/Caffe2ModelLoader.cpp
  lib/Importer/ONNXModelLoader.cpp
Labels: CLA Signed

#2015 [image] Factor out PNG processing
  include/glow/Base/Image.h
  lib/Base/Image.cpp
  tools/loader/ImageClassifier.cpp
Labels: CLA Signed

#2019 [GraphOptimizer] Fuse RescaleNodes down into MatMulNodes
  lib/Optimizer/GraphOptimizer.cpp
  tests/unittests/graphOptzTest.cpp
Labels: CLA Signed

#2018 [examples] Add cmake for ResNet50 bundle
  examples/CMakeLists.txt
  examples/bundles/CMakeLists.txt
  examples/bundles/resnet50/CMakeLists.txt
  examples/bundles/resnet50/Makefile
  examples/bundles/resnet50/main.cpp
Labels: CLA Signed

#2021 [build] Do not build bundles by default. It takes 40min on CI.
  CMakeLists.txt
  examples/bundles/CMakeLists.txt
Labels: CLA Signed

#2011 [IRBuilder] support create weight with quantize type
  include/glow/IR/IRBuilder.h
  lib/IR/IRBuilder.cpp
Labels: CLA Signed

#2020 [onnx loaders] Support Gather ops in onnxifi loader.
  include/glow/Importer/CommonOperatorLoader.h
  lib/Importer/Caffe2ModelLoader.cpp
  lib/Importer/ONNXIFIModelLoader.cpp
  tests/models/onnxModels/gather.onnxtxt
  tests/unittests/onnxImporterTest.cpp
Labels: CLA Signed

#2031 [Readme] add a link to the roadmap page.
  README.md
Labels: CLA Signed

#2030 Support int32 index for Gather
  include/glow/Graph/VerifierHelper.h
  lib/Backends/CPU/LLVMIRGen.cpp
  lib/Backends/CPU/libjit/libjit.cpp
  lib/Backends/Interpreter/InterpreterFunction.h
  lib/Backends/Interpreter/InterpreterNodes.cpp
  lib/Graph/Nodes.cpp
  lib/Graph/VerifierHelper.cpp
  lib/Importer/ONNXIFIModelLoader.cpp
  tests/models/onnxModels/gather.onnxtxt
  tests/unittests/OperatorTest.cpp
  tests/unittests/onnxImporterTest.cpp
  tools/ClassGen/InstrGen.cpp
Labels: CLA Signed

#2034 [trivial] Rewrote some duplicated code.
  lib/Graph/Graph.cpp
Labels: CLA Signed

#2009 [utils] Add driver for determining imagenet topk accuracy
  docs/Testing.md
  utils/imagenet_topk_accuracy_driver.py
Labels: CLA Signed

#2032 [GraphOptimizer] Only fuse Rescales into input if input has one user
  lib/Optimizer/GraphOptimizer.cpp
  tests/unittests/graphOptzTest.cpp
Labels: CLA Signed

#2038 [cleanup | NFC] Remove many unnecessary uses of getNthInput()
  tests/unittests/BackendTest.cpp
  tests/unittests/caffe2ImporterTest.cpp
  tests/unittests/graphOptzTest.cpp
  tests/unittests/onnxImporterTest.cpp
Labels: CLA Signed

#2027 [Verifier] Switch the node verifier from assert to returning bool for the function and module
  include/glow/Graph/Graph.h
  include/glow/Graph/VerifierHelper.h
  lib/Converter/FunctionConverter.cpp
  lib/ExecutionEngine/ExecutionEngine.cpp
  lib/Graph/Graph.cpp
  lib/Graph/VerifierHelper.cpp
  lib/IR/IRGen.cpp
  tests/unittests/graphGradTest.cpp
  tests/unittests/graphTest.cpp
  tests/unittests/typeAToTypeBFunctionConverterTest.cpp
Labels: CLA Signed

#2042 [verifier] Make template argument deduction happy (gcc 4.8)
  lib/Graph/Nodes.cpp
  lib/Graph/VerifierHelper.cpp
Labels: CLA Signed

#2050 [nfc] Move image processing cli args to Image.{h,cpp}
  include/glow/Base/Image.h
  lib/Base/Image.cpp
  tools/loader/ImageClassifier.cpp
Labels: CLA Signed

#2049 [image-classifier] Remove dead code
  tools/loader/ImageClassifier.cpp
Labels: CLA Signed

#2055 [docs] Add a nits checklist to CodingStandards
  docs/CodingStandards.md
Labels: CLA Signed

#2054 [image] Improve preprocessing command line options
  include/glow/Base/Image.h
  lib/Base/Image.cpp
Labels: CLA Signed

#2029 [onnxifi] Check capacity in onnxGetBackendIDs before writing backendIDs
  lib/Onnxifi/onnxifiGlow.cpp
Labels: CLA Signed

#2062 README Updates for OpenCL on Ubuntu
  README.md
Labels: CLA Signed

#2061 [doc] Add ArrayRef to coding standards checklist
  docs/CodingStandards.md
Labels: CLA Signed

#2058 [BackendUtils]Convert RuntimeBundle to a class
  include/glow/Backends/BackendUtils.h
  include/glow/Backends/CompiledFunction.h
  lib/Backends/BackendUtils.cpp
  lib/Backends/CPU/AllocationsInfo.h
  lib/Backends/CPU/CPUFunction.cpp
  lib/Backends/CPU/CPUFunction.h
  lib/Backends/Interpreter/InterpreterFunction.cpp
  lib/Backends/Interpreter/InterpreterFunction.h
  lib/Backends/OpenCL/OpenCL.cpp
  lib/Backends/OpenCL/OpenCL.h
Labels: CLA Signed

#2035 [examples] Add cmake for LeNet MNIST bundle
  examples/bundles/CMakeLists.txt
  examples/bundles/lenet_mnist/CMakeLists.txt
  examples/bundles/lenet_mnist/Makefile
  examples/bundles/lenet_mnist/main.cpp
Labels: CLA Signed

#2066 Prevent errors from use of deprecated OpenCL 1.2 function
  lib/Backends/OpenCL/OpenCL.cpp
Labels: CLA Signed

#2063 [docs] Delete superfluous bundles and update bundle docs
  CMakeLists.txt
  docs/AOT.md
  examples/CMakeLists.txt
  examples/bundles/resnet50/Makefile
  examples/bundles/vgg19/Makefile
  examples/bundles/vgg19/vgg19.cpp
  examples/bundles/zfnet512/Makefile
  examples/bundles/zfnet512/zfnet512.cpp
Labels: CLA Signed

#2052 [image] Fix build when libpng not found
  CMakeLists.txt
  include/glow/Base/Image.h
  lib/Base/CMakeLists.txt
  lib/Base/Image.cpp
  tests/unittests/CMakeLists.txt
Labels: CLA Signed

#2070 [docs] Direct link to glow topic on forums
  README.md
Labels: CLA Signed

#2074 [trivial] Remove debug message in CMakeLists
  lib/Base/CMakeLists.txt
Labels: CLA Signed

#2075 Add vertical whitespace between top-level definitions
  include/glow/Backends/BackendUtils.h
  include/glow/Graph/Node.h
  lib/Backends/BackendUtils.cpp
  lib/Backends/CPU/AllocationsInfo.cpp
  lib/Backends/CPU/AllocationsInfo.h
  lib/Backends/CPU/libjit/libjit.cpp
  lib/Backends/Interpreter/InterpreterFunction.cpp
  lib/Backends/OpenCL/OpenCL.cpp
  lib/Graph/Graph.cpp
  lib/Graph/Node.cpp
  lib/Graph/Nodes.cpp
  lib/IR/IRBuilder.cpp
  lib/Optimizer/IROptimizer.cpp
  lib/Optimizer/Lower.cpp
Labels: CLA Signed

#2076 [tests] add the generation of xml google test reports
  tests/unittests/CMakeLists.txt
Labels: CLA Signed

#2085 [trivial] Fix spelling of ProtobufLoader
  tools/loader/ImageClassifier.cpp
Labels: CLA Signed

#2077 [Quantization] Dequantize(rescale) -> Dequantize()
  lib/Optimizer/GraphOptimizer.cpp
  tests/unittests/graphOptzTest.cpp
  tests/unittests/quantizationTest.cpp
Labels: CLA Signed

#2084 [quantization] fix Tensor zero() and isZero() to respect quantized offset
  include/glow/Base/Tensor.h
  tests/unittests/tensorsTest.cpp
Labels: CLA Signed

#2087 [image-classifier] Commonalize command line arguments to hyphen-style
  docs/AOT.md
  docs/ModelLoader.md
  docs/Quantization.md
  docs/Testing.md
  examples/bundles/lenet_mnist/CMakeLists.txt
  examples/bundles/lenet_mnist/Makefile
  examples/bundles/resnet50/CMakeLists.txt
  examples/fr2en.cpp
  include/glow/Base/Image.h
  lib/Base/Image.cpp
  tests/images/run.sh
  tools/loader/ImageClassifier.cpp
  tools/loader/Loader.cpp
  tools/loader/TextTranslator.cpp
  utils/imagenet_topk_accuracy_driver.py
Labels: CLA Signed

#2086 [Quantization] Allow the input and output of a quantized AvgPool node have different quantization param.
  lib/Graph/Nodes.cpp
  lib/Quantization/Quantization.cpp
  tests/unittests/quantizationTest.cpp
Labels: CLA Signed

#2089 [image] clean up after failing to read a png image
  lib/Base/Image.cpp
  tests/images/other/corrupt_dog.png
  tests/unittests/imageTest.cpp
Labels: CLA Signed

#2093 [Quantization] Improve RowwiseQuantizedFullyConnected node to support int32 quantized bias.
  lib/Backends/CPU/libjit/libjit_matmul.cpp
  lib/Backends/Interpreter/InterpreterNodes.cpp
  lib/Graph/Graph.cpp
  tests/unittests/OperatorTest.cpp
Labels: CLA Signed

#2094 [tensor] Add insertSlice to insert sub-regions of a tensor
  include/glow/Base/Tensor.h
  tests/unittests/tensorsTest.cpp
  tools/loader/ImageClassifier.cpp
Labels: CLA Signed

#2095 [examples] Simple example of loading a protobuf
  examples/CMakeLists.txt
  examples/lenet-loader.cpp
Labels: CLA Signed

#2099 [grammar] Fix 'the the' occurences.
  lib/Backends/CPU/AllocationsInfo.cpp
  lib/Backends/CPU/libjit/libjit_conv.cpp
  lib/Optimizer/GraphOptimizer.cpp
  lib/Optimizer/IROptimizer.cpp
Labels: CLA Signed

#2096 [Caffe2ModelLoader] Load GivenTensorIntFill using int32_t
  lib/Importer/Caffe2ModelLoader.cpp
  tests/models/caffe2Models/empty_predict_net.pbtxt
  tests/models/caffe2Models/fill_test_init_net.pbtxt
  tests/unittests/caffe2ImporterTest.cpp
Labels: CLA Signed

#2079 [Error Handling] Add Error handling to model importer related code
  examples/CMakeLists.txt
  examples/lenet-loader.cpp
  include/glow/Importer/Caffe2ModelLoader.h
  include/glow/Importer/CommonOperatorLoader.h
  include/glow/Importer/ONNXIFIModelLoader.h
  include/glow/Importer/ONNXModelLoader.h
  include/glow/Importer/ProtobufLoader.h
  include/glow/Support/Error.h
  lib/Importer/Caffe2ModelLoader.cpp
  lib/Importer/ONNXIFIModelLoader.cpp
  lib/Importer/ONNXModelLoader.cpp
  lib/Importer/ProtobufLoader.cpp
  lib/Onnxifi/Base.cpp
  lib/Support/CMakeLists.txt
  lib/Support/Error.cpp
  tests/unittests/caffe2ImporterTest.cpp
  tests/unittests/onnxImporterTest.cpp
  tools/loader/ImageClassifier.cpp
  tools/loader/ModelRunner.cpp
  tools/loader/TextTranslator.cpp
Labels: CLA Signed

#2090 [NodeGen] Support enum members on nodes
  tools/ClassGen/CMakeLists.txt
  tools/ClassGen/MemberType.cpp
  tools/ClassGen/MemberType.h
  tools/ClassGen/NodeBuilder.cpp
  tools/ClassGen/NodeBuilder.h
Labels: CLA Signed
